20210946_김다은_xor_Multiple Layer Perceptron 실습

In [110]:
import torch
from torch import nn
import torch.optim as optim
from matplotlib import pyplot as plt
import numpy as np

In [111]:
# XOR
X = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float)
Y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float)

In [112]:
class XOR(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(2, 2),
            nn.Linear(2, 1)
        )

    def forward(self, x):
        return self.model(x)

In [113]:
xor_model = XOR()
xor_model

XOR(
  (model): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): Linear(in_features=2, out_features=1, bias=True)
  )
)

In [114]:
w_xor = torch.zeros(2, requires_grad=True)
b_xor = torch.zeros(1, requires_grad=True)
w_xor, b_xor

(tensor([0., 0.], requires_grad=True), tensor([0.], requires_grad=True))

In [115]:
hypothesis = (X @ w_xor + b_xor)
hypothesis

tensor([0., 0., 0., 0.], grad_fn=<AddBackward0>)

In [116]:
# XOR gate

# initialize parameter
w_xor = torch.zeros(2, requires_grad=True)
b_xor = torch.zeros(1, requires_grad=True)

# hyperparameter
def train(model, X, Y, epochs=1000, lr=0.1):
  optimizer = optim.SGD([w_xor, b_xor], lr=lr)
  loss_fn = nn.BCEWithLogitsLoss()

  for epoch in range(epochs):
    hypothesis = X @ w_xor + b_xor
    cost = loss_fn(hypothesis.view(-1,1), Y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print(f'Epoch: {epoch}, Loss: {cost}')
  print('cost:', cost)
  print('Parameters:', w_xor, b_xor)


In [117]:
def predict(x, model=None):
    with torch.no_grad():
        prediction = model(torch.tensor(x, dtype=torch.float).view(1, -1))
        prediction = torch.where(prediction >= 0.5, torch.tensor(1.0), torch.tensor(0.0))
        return prediction.item()

In [118]:
model = XOR()
train(model, X, Y)

Epoch: 0, Loss: 0.6931471824645996
Epoch: 100, Loss: 0.6931471824645996
Epoch: 200, Loss: 0.6931471824645996
Epoch: 300, Loss: 0.6931471824645996
Epoch: 400, Loss: 0.6931471824645996
Epoch: 500, Loss: 0.6931471824645996
Epoch: 600, Loss: 0.6931471824645996
Epoch: 700, Loss: 0.6931471824645996
Epoch: 800, Loss: 0.6931471824645996
Epoch: 900, Loss: 0.6931471824645996
cost: tensor(0.6931, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Parameters: tensor([0., 0.], requires_grad=True) tensor([0.], requires_grad=True)


In [119]:
def predict(x, w=None, b=None):
    return (x @ w + b)

In [120]:
predict(X, w=w_xor, b=b_xor)

tensor([0., 0., 0., 0.], grad_fn=<AddBackward0>)

In [121]:
torch.where(predict(X, w=w_xor, b=b_xor)>0.5, 1., 0.)

tensor([0., 0., 0., 0.])

In [122]:
for x in X:
  prediction = model(torch.FloatTensor(x).view(1, -1))
  print(x.tolist(), {prediction})

[0.0, 0.0] {tensor([[0.2351]], grad_fn=<AddmmBackward0>)}
[0.0, 1.0] {tensor([[-0.0669]], grad_fn=<AddmmBackward0>)}
[1.0, 0.0] {tensor([[0.0902]], grad_fn=<AddmmBackward0>)}
[1.0, 1.0] {tensor([[-0.2118]], grad_fn=<AddmmBackward0>)}
